// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxvavdiofqggciybqslt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dmF2ZGlvZnFnZ2NpeWJxc2x0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTYyNjcsImV4cCI6MjA3MzY5MjI2N30.kiiRyef3DKcQrWHwr_Qe4LeYBPI4PVOX6GBbUio3USc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});